### ISSUE TITLE
bundle doesn't contain comments with module IDs

### ISSUE THREAD

**Issue by musab** [electrode-io/electrode-bundle-analyzer#2]
When running

`./node_modules/.bin/analyze-bundle -b dist/bundle.js -s stats.json `

I receive: `analyze-bundle: bundle doesn't contain comments with module IDs, can't analyze`

When viewing the bundle.js I can see the module IDs commented as:  `/* 1 */` all the way to `/* 62 */`

The steps I am taking are: 

1. `./node_modules/.bin/webpack --env production --json > stats.json`
2. `./node_modules/.bin/analyze-bundle -b dist/bundle.js -s stats.json`

Is there an option I maybe missing?

**Comment by edi9999** [comment]
Did you find out what is causing this ? 

It seems to me that webpack forgets to output the `/* 1 */`  since I upgraded to webpack 4.
